import os
import json
import logging
import random
from typing import List, Dict, Any, Optional
from gigachat import GigaChat
from gigachat.models import Chat, Messages, MessagesRole
from database.models import User
from config import config

logger = logging.getLogger(__name__)

client = GigaChat(
    credentials=config.GIGACHAT_API_KEY,
    verify_ssl_certs=False,
    model=config.GIGACHAT_MODEL
)

# ----- ОГРОМНАЯ БАЗА ТРЕКОВ (НАЗВАНИЕ - ИСПОЛНИТЕЛЬ) -----
POPULAR_SONGS = [
    "Bohemian Rhapsody - Queen",
    "Imagine - John Lennon",
    "Hotel California - Eagles",
    "Stairway to Heaven - Led Zeppelin",
    "Smells Like Teen Spirit - Nirvana",
    "Billie Jean - Michael Jackson",
    "Hey Jude - The Beatles",
    "Yesterday - The Beatles",
    "Shape of You - Ed Sheeran",
    "Uptown Funk - Mark Ronson ft. Bruno Mars",
    "Despacito - Luis Fonsi ft. Daddy Yankee",
    "Waka Waka - Shakira",
    "Rolling in the Deep - Adele",
    "Someone Like You - Adele",
    "Bad Guy - Billie Eilish",
    "Blinding Lights - The Weeknd",
    "Levitating - Dua Lipa",
    "Montero - Lil Nas X",
    "Stay - The Kid LAROI, Justin Bieber",
    "Peaches - Justin Bieber",
    "Lose Yourself - Eminem",
    "Stan - Eminem ft. Dido",
    "The Real Slim Shady - Eminem",
    "Without Me - Eminem",
    "Rap God - Eminem",
    "God's Plan - Drake",
    "Sicko Mode - Travis Scott",
    "Goosebumps - Travis Scott",
    "My Beautiful Dark Twisted Fantasy - Kanye West",
    "To Pimp a Butterfly - Kendrick Lamar",
    "The Dark Side of the Moon - Pink Floyd",
    "Wish You Were Here - Pink Floyd",
    "Led Zeppelin IV - Led Zeppelin",
    "Physical Graffiti - Led Zeppelin",
    "Houses of the Holy - Led Zeppelin",
    "Back in Black - AC/DC",
    "Highway to Hell - AC/DC",
    "Thunderstruck - AC/DC",
    "Sweet Child O' Mine - Guns N' Roses",
    "November Rain - Guns N' Roses",
    "Welcome to the Jungle - Guns N' Roses",
    "Enter Sandman - Metallica",
    "Nothing Else Matters - Metallica",
    "The Unforgiven - Metallica",
    "Fade to Black - Metallica",
    "Master of Puppets - Metallica",
    "One - Metallica",
    "Paranoid - Black Sabbath",
    "Iron Man - Black Sabbath",
    "War Pigs - Black Sabbath",
    "Kashmir - Led Zeppelin",
    "Whole Lotta Love - Led Zeppelin",
    "Comfortably Numb - Pink Floyd",
    "Another Brick in the Wall - Pink Floyd",
    "We Will Rock You - Queen",
    "We Are the Champions - Queen",
    "Don't Stop Me Now - Queen",
    "Somebody to Love - Queen",
    "Crazy Little Thing Called Love - Queen",
    "I Want to Break Free - Queen",
    "Radio Ga Ga - Queen",
    "Under Pressure - Queen & David Bowie",
    "Beat It - Michael Jackson",
    "Thriller - Michael Jackson",
    "Bad - Michael Jackson",
    "Smooth Criminal - Michael Jackson",
    "The Way You Make Me Feel - Michael Jackson",
    "Man in the Mirror - Michael Jackson",
    "Black or White - Michael Jackson",
    "Like a Rolling Stone - Bob Dylan",
    "Blowin' in the Wind - Bob Dylan",
    "The Times They Are a-Changin' - Bob Dylan",
    "Take It Easy - Eagles",
    "Desperado - Eagles",
    "New Kid in Town - Eagles",
    "Lyin' Eyes - Eagles",
    "Tequila Sunrise - Eagles",
    "Rock and Roll - Led Zeppelin",
    "Black Dog - Led Zeppelin",
    "Immigrant Song - Led Zeppelin",
    "The Ocean - Led Zeppelin",
    "Misty Mountain Hop - Led Zeppelin",
    "Another One Bites the Dust - Queen",
    "Beautiful Boy - John Lennon",
    "Woman - John Lennon",
    "Let It Be - The Beatles",
    "Something - The Beatles",
    "Here Comes the Sun - The Beatles",
    "Come Together - The Beatles",
    "Penny Lane - The Beatles",
    "Strawberry Fields Forever - The Beatles",
    "Yellow Submarine - The Beatles",
    "Eleanor Rigby - The Beatles",
    "The Sound of Silence - Simon & Garfunkel",
    "Bridge over Troubled Water - Simon & Garfunkel",
    "Mrs. Robinson - Simon & Garfunkel",
    "California Dreamin' - The Mamas & the Papas",
    "Monday Monday - The Mamas & the Papas",
    "I Got You Babe - Sonny & Cher",
    "Good Vibrations - The Beach Boys",
    "Wouldn't It Be Nice - The Beach Boys",
    "God Only Knows - The Beach Boys",
    "Sloop John B - The Beach Boys",
    "Kokomo - The Beach Boys",
    "Surfin' USA - The Beach Boys",
    "I Heard It Through the Grapevine - Marvin Gaye",
    "What's Going On - Marvin Gaye",
    "Sexual Healing - Marvin Gaye",
    "Let's Get It On - Marvin Gaye",
    "Ain't No Mountain High Enough - Marvin Gaye & Tammi Terrell",
    "Respect - Aretha Franklin",
    "Think - Aretha Franklin",
    "Natural Woman - Aretha Franklin",
    "Chain of Fools - Aretha Franklin",
    "Son of a Preacher Man - Dusty Springfield",
    "Piece of My Heart - Janis Joplin",
    "Proud Mary - Creedence Clearwater Revival",
    "Rollin' on the River - Creedence Clearwater Revival",
    "Fortunate Son - Creedence Clearwater Revival",
    "Born to Run - Bruce Springsteen",
    "Thunder Road - Bruce Springsteen",
    "Badlands - Bruce Springsteen",
    "Hungry Heart - Bruce Springsteen",
    "Dancing in the Dark - Bruce Springsteen",
    "The River - Bruce Springsteen",
    "Born in the U.S.A. - Bruce Springsteen",
    "I'm on Fire - Bruce Springsteen",
    "Glory Days - Bruce Springsteen",
    "Paradise City - Guns N' Roses",
    "Knockin' on Heaven's Door - Guns N' Roses",
    "Don't Cry - Guns N' Roses",
    "Livin' on a Prayer - Bon Jovi",
    "You Give Love a Bad Name - Bon Jovi",
    "It's My Life - Bon Jovi",
    "Bad Medicine - Bon Jovi",
    "Wanted Dead or Alive - Bon Jovi",
    "Blaze of Glory - Bon Jovi",
    "The Show Must Go On - Queen",
    "Love of My Life - Queen",
    "Killer Queen - Queen",
    "Bicycle Race - Queen",
    "Fat Bottomed Girls - Queen",
    "Шадэ - By Индия, Xcho & МОТ",
    "Экспонат - Mia Boyka",
    "Gaz - Zivert",
    "Мальборо - Sayan",
    "Феникс - Bearwolf",
    "Омут - Полка & Yasmi",
    "Не звони - Ramil’",
    "Калинка - Miravi",
    "59-я широта - Jah Khalib",
    "Гостиница - Элджей",
    "Тону - Hollyflame",
    "Ворона - Кэнни & МС Дымка",
    "Матушка - Татьяна Куртукова",
    "Под Новый Год - Betsy & Ded M",
    "I Got Love - Miyagi & Эндшпиль & Рем Дигга",
    "Жиганская - Jakone & Kiliana",
    "Nobody - Aarne, Toxi & Big Baby Tape",
    "Sigma Boy - Betsy & Мария Янковская",
    "С днем рождения - Ирина Аллегрова",
    "Седая ночь - Юрий Шатунов",
    "Королева снежная - Комиссар",
    "Ты уйдёшь - Комиссар",
    "Ничего не говори - Рок-острова",
    "Чистый лист - НЭНСИ",
    "Гранитный камушек - Божья Коровка",
    "Не бойся - Юрий Шатунов",
    "А река течет - Любэ",
    "Белые розы - Ласковый май",
    "Ring My Bell - Anita Ward",
    "Лиловый негр - Антоха MC",
    "Боюсь - Sound From R.K",
    "Между нами война - Sound From R.K",
    "Dawn FM - The Weeknd",
    "No Ordinary Love - Sade",
    "Back to Black - Amy Winehouse",
    "Приятная - Эндшпиль feat. Ollane",
    "Daddy Cool - Boney M.",
    "Deja Vu - Beyoncé feat. JAY-Z",
    "Disturbia - Rihanna",
    "Остров - Леонид Агутин",
    "Levanter - Stray Kids",
    "Automatic - The Pointer Sisters",
    "Dai Dai - Shakira & Burna Boy",
    "Swim - BTS",
    "Beauty And A Beat - Justin Bieber ft. Nicki Minaj",
    "Babydoll - Dominic Fike",
    "Wonderwall - Oasis",
    "The One That Got Away - Katy Perry",
    "Back to Friends - Sombr",
    "End of Beginning - Djo",
    "Худи - Джиган, Artik & Asti, Niletto",
    "Базовый минимум - Sabi, Mia Boyka",
    "Банк - Icegergert & Zivert",
    "Баяноммай - Артем Тото",
    "Я твой номер один - Дима Билан",
    "Ты не мой - Света",
    "Ай-яй-яй - Руки Вверх!",
    "Просто неземная - Эд Изместьев",
    "А лето цвета - Юрий Шатунов",
    "Шпилька-каблучок - Лолита",
    "Showdown - shadowraze",
    "Astral step - shadowraze",
    "Лёд - WENARO w/ LXNER",
    "Adaptive strike - shadowraze w/ LXNER, quiizzzmeow",
    "Фотографирую закат - fem.love",
    "Shadowfiend - shadowraze",
    "Плачь - rizza w/ Sqwore",
    "Juggernaut - shadowraze",
    "Silver Night - Bad Style & Tender May",
    "XV Лет спустя - Баста & Гуф",
    "Улицам нужен твой огонь - Basta & Guf",
    "Тают дни - Баста & Гуф",
    "В сигаретном дыму - Basta & Guf",
    "Из песни слов не выкинешь - Баста & Гуф",
    "Чайный пьяница 2.0 - Баста & Гуф",
    "БХРР - Баста & Гуф",
    "Муравейник - Баста & Гуф",
    "Как сам - Баста & Гуф",
    "Дедули - Баста & Гуф",
    "Кривые зеркала - Баста & Гуф",
    "Колизей - Баста & Гуф",
    "Над Москва-Рекой - Баста & Гуф",
    "Beni Al - Ankara Echoes",
    "Go - The Chemical Brothers feat. Q-Tip",
    "КУКЛА - Diskoteka Avariya feat. VONAMOUR",
    "Dirty Diana - Michael Jackson",
    "Сыпь, гармоника! - СДП",
    "Асфальт - Jakone & Kiliana",
    "Human Nature - Michael Jackson",
    "Шёлк - Ваня Дмитриенко",
    "Come Over - BTS",
    "The Fate of Ophelia - Taylor Swift",
    "Golden - HUNTR/X & KPop Demon Hunters Cast",
    "Ordinary - Alex Warren",
    "Man I Need - Olivia Dean",
    "Choosin’ Texas - Ella Langley",
    "DtMF - Bad Bunny",
    "BAILE INoLVIDABLE - Bad Bunny",
    "Janice STFU - Drake",
    "Be Her - Ella Langley",
    "Shabang - Drake",
    "the cure - Olivia Rodrigo",
    "I Just Might - Bruno Mars",
    "Opalite - Taylor Swift",
    "Aperture - Harry Styles",
    "Drop Dead - Olivia Rodrigo",
    "Cryogen - Muse",
    "Bubbling - Noga Erez",
    "Something heavy - Jacob Collier",
    "The boy who played the harp - Dave",
    "Limbo - Igorrr",
    "Andromeda - Lelek",
    "Trojan horse - Kwizma",
    "Rein Me In - Sam Fender & Olivia Dean",
    "Dracula - Tame Impala",
    "Raindance - Dave feat. Tems",
    "Where Is My Husband! - Raye",
    "iloveitiloveitiloveit - Bella Kay",
    "Разбуди - (неизв.)",
    "Медленно - (неизв.)",
    "Снова напьешься - (неизв.)",
    "Буду любить тебя - (неизв.)",
    "Отпусти - (неизв.)",
    "Без тебя - (неизв.)",
    "Весенний вайб - (неизв.)",
    "Не спеши - (неизв.)",
    "Ты проиграл - (неизв.)",
    "Не вспоминай - (неизв.)",
    "Я всё ещё свет - (неизв.)",
    "Розовый закат - (неизв.)",
    "Я улечу - (неизв.)",
    "Кукла - (неизв.)",
    "Только ты - (неизв.)",
    "Ты такая одна - (неизв.)",
    "Твои глаза - (неизв.)",
    "Мало тебя - (неизв.)",
    "Улетай - (неизв.)",
    "Глупая девочка - (неизв.)",
    "Прости - (неизв.)",
    "Танцуй - (неизв.)",
    "Не отпускай - (неизв.)",
    "Услышит весь район - DABRO",
    "Сочи-Киров-Ростов - Galibri & Mavik",
    "Малиновый свет - Леша Свик",
    "Одного - Татьяна Куртукова",
    "Ой, какая ты - Хабиб",
    "Ночь - CHEBANOV",
    "Одинокая нежная - Филипп Киркоров",
    "Levels - Avicii",
    "Don’t You Worry Child - Swedish House Mafia",
    "Reload - Sebastian Ingrosso, Tommy Trash, John Martin",
    "High On Life - Martin Garrix, Bonn",
    "Calling - Sebastian Ingrosso, Alesso, Ryan Tedder",
    "If I Lose Myself - OneRepublic & Alesso",
    "Spaceman - Hardwell",
    "Blah Blah Blah - Armin van Buuren",
    "Mammoth - Dimitri Vegas & Like Mike, MOGUAI",
    "Titanium - David Guetta & Sia",
    "APT. - ROSÉ & Bruno Mars",
    "luther - Kendrick Lamar & SZA",
    "Die With A Smile - Lady Gaga & Bruno Mars",
    "Not Like Us - Kendrick Lamar",
    "BIRDS OF A FEATHER - Billie Eilish",
    "Abracadabra - Lady Gaga",
    "Nuevayol - Bad Bunny",
    "Manchild - Sabrina Carpenter",
    "Militantum - Темный Принц",
    "Arirang - BTS",
    "Баста/Гуф 2026 - Баста & Гуф",
    "Papaoutai - Stromae",
    "WILDFLOWER - Billie Eilish",
    "American Girls - Harry Styles",
    "Risk It All - Bruno Mars",
    "Folded - Kehlani",
    "Tití me preguntó - Bad Bunny",
    "So Easy - Olivia Dean",
    "Whisper My Name - (неизв.)",
    "Dat it der al is - Nynke Laverman",
    "Deep time - Boards of Canada",
    "4.5.0. - Daughters of Donbas, Marichka",
    "Fabienk - Angine de Poitrine",
    "Boots on the ground - Massive Attack + Tom Waits",
    "Nathenas - Stelios Petrakis",
    "Forget-me-not - Laufey + Iceland symphony orchestra",
    "Good citizen - Iyah May",
    "Aan alaxchyn - Snow raven",
    "Ruht wohl, ihr heiligen gebeine - Pygmalion, Raphaël Pichon",
    "Luukered - Sadu",
    "Introit / Prophecy at 1420 MHz - Boards of Canada",
    "All one - Vini vici, Giorgia Angiuli, Volcano on Mars",
    "Nân - Alis",
    "Big fish - Nate Smith + säje",
    "Over you - Hermitude",
    "Damme nu ricciu - Raül Refree + Maria Mazzotta",
    "Winny - Fred again.., Sammy Virji, Winny",
    "In battere - Katatonic silentio",
    "She knows too much - Thundercat + Mac miller",
    "NOS - Blawan",
    "Little lord fentanyl - Primus, Puscifer",
    "Sayōnara - Kneecap + Paul Hartnoll",
    "Туман - Гуф",
    "Purosangue - Jakone & MACAN",
    "KARMA - Egor Kreed & ARTIK & ASTI",
    "кавалерия - By Индия",
    "Mallorca - gleb filipchenkow, G-POL & Jeam Biscuit",
    "Силуэт - Ваня Дмитриенко & Аня Пересильд",
    "День Победы - Лев Лещенко",
    "Спящая красавица - Noize MC",
    "Movin' To The Sun - HUGEL, Imael Angel & Ultra Naté",
    "Мало 2.0 - Egor Kreed feat. OG Buda, Toxi, Мэйби Бэйби, Baby Cute, Дора, madk1d & тёмный принц",
    "Bad Habits - Ed Sheeran",
    "New Rules - Dua Lipa",
    "One More Night - Maroon 5",
    "Perfect - Ed Sheeran",
    "Shivers - Ed Sheeran",
    "Girls Like You - Maroon 5",
    "See You Again - Wiz Khalifa ft. Charlie Puth",
    "Memories - Maroon 5",
    "There's Nothing Holdin' Me Back - Shawn Mendes",
    "I'm a Mess - Bebe Rexha",
    "Solo - Clean Bandit ft. Demi Lovato",
    "Calm Down - Rema, Selena Gomez",
    "Diamonds - Rihanna",
    "Kings & Queens - Ava Max",
    "Houdini - Dua Lipa",
    "Let Me Love You - DJ Snake ft. Justin Bieber",
    "We Can't Be Friends - Ariana Grande",
    "Symphony - Clean Bandit ft. Zara Larsson",
    "Rockabye - Clean Bandit ft. Sean Paul & Anne-Marie",
    "Salt - Ava Max",
    "Save Your Tears - The Weeknd",
    "Пропаганда - Тарантино",
    "Мне тебя так мало - 140 ударов в минуту",
    "Замело - Misty",
    "Беги - Татьяна Третьяк",
    "Гордиев узел - Ария",
    "Фрау чёрная смерть - Radio Tapok",
    "Moment - #KEMM",
    "Turn It Around - 4 Strings, CJ Stone, Alena",
    "Снежная королева - AIAlina Belova",
    "Хочу замуж - AIAlina Belova",
    "1000 ярдов - AIAlina Belova",
    "Take Me to Church - Hozier",
    "Thinking Out Loud - Ed Sheeran",
    "Photograph - Ed Sheeran",
    "Castle on the Hill - Ed Sheeran",
    "Galway Girl - Ed Sheeran",
    "Happier - Ed Sheeran",
    "Perfect Symphony - Ed Sheeran ft. Andrea Bocelli",
    "I Don't Care - Ed Sheeran & Justin Bieber",
    "Beautiful People - Ed Sheeran ft. Khalid",
    "South of the Border - Ed Sheeran ft. Camila Cabello",
    "Afterglow - Ed Sheeran",
    "The Joker And The Queen - Ed Sheeran ft. Taylor Swift",
    "Eyes Closed - Ed Sheeran",
    "Boat - Ed Sheeran",
    "Life Goes On - Ed Sheeran",
    "Celestial - Ed Sheeran",
    "F64 - Ed Sheeran",
    "Stoned on You - Jaymes Young",
    "Infinity - Jaymes Young",
    "Happiest Year - Jaymes Young",
    "Feel Something - Jaymes Young",
    "I'll Be Good - Jaymes Young",
    "Dark Side - Bishop Briggs",
    "River - Bishop Briggs",
    "Wild Horses - Bishop Briggs",
    "Dreams - Fleetwood Mac",
    "Go Your Own Way - Fleetwood Mac",
    "Don't Stop - Fleetwood Mac",
    "The Chain - Fleetwood Mac",
    "Rhiannon - Fleetwood Mac",
    "Landslide - Fleetwood Mac",
    "Everywhere - Fleetwood Mac",
    "Little Lies - Fleetwood Mac",
    "Seven Wonders - Fleetwood Mac",
    "Big Love - Fleetwood Mac",
    "Tusk - Fleetwood Mac",
    "Sara - Fleetwood Mac",
    "Gypsy - Fleetwood Mac",
    "Hold Me - Fleetwood Mac",
    "Carry On - Crosby, Stills, Nash & Young",
    "Suite: Judy Blue Eyes - Crosby, Stills & Nash",
    "Ohio - Crosby, Stills, Nash & Young",
    "Teach Your Children - Crosby, Stills, Nash & Young",
    "Our House - Crosby, Stills, Nash & Young",
    "Southern Cross - Crosby, Stills & Nash",
    "Woodstock - Joni Mitchell",
    "Big Yellow Taxi - Joni Mitchell",
    "Both Sides Now - Joni Mitchell",
    "A Case of You - Joni Mitchell",
    "California - Joni Mitchell",
    "Help Me - Joni Mitchell",
    "Free Man in Paris - Joni Mitchell",
    "You Turn Me On I'm a Radio - Joni Mitchell",
    "Плакучая ива - Любэ",
    "Там, за туманами - Любэ",
    "Позови меня тихо по имени - Любэ",
    "Давай за... - Любэ",
    "Не валяй дурака, Америка - Любэ",
    "За высоким забором - Любэ",
    "Главное, что есть ты - Любэ",
    "Прорвёмся! - Любэ",
    "А зори здесь тихие - Любэ",
    "Старый барин - Любэ",
    "Конь - Любэ",
    "По высокой траве - Любэ",
    "Ишь ты - Любэ",
    "Солнце встаёт - Любэ",
    "Шагом марш - Любэ",
    "Солдат - Любэ",
    "Березы - Любэ",
    "Песня о земле - Любэ",
    "От Волги до Енисея - Любэ",
    "За тебя, Родина-мать - Любэ",
    "Королева - Натали",
    "Ветер с моря дул - Натали",
    "Считалочка - Натали",
    "О, Боже, какой мужчина - Натали",
    "Поезд на Ленинград - Натали",
    "Я - не ангел - Натали",
    "Мне нравится - Натали",
    "Ты - моя - Натали",
    "Звезда по имени Солнце - Кино",
    "Группа крови - Кино",
    "Кукушка - Кино",
    "Пачка сигарет - Кино",
    "В наших глазах - Кино",
    "Хочу перемен! - Кино",
    "Печаль - Кино",
    "Спокойная ночь - Кино",
    "Когда твоя девушка больна - Кино",
    "Апрель - Кино",
    "Камчатка - Кино",
    "Закрой за мной дверь - Кино",
    "Мама, мы все тяжело больны - Кино",
    "Это не любовь - Кино",
    "Мы ждем перемен - Кино",
    "Следи за собой - Кино",
    "Война - Кино",
    "Бездельник - Кино",
    "Электричка - Кино",
    "Нам с тобой - Кино",
    "Мои друзья - Кино",
    "Легенда - Кино",
    "Место для шага вперёд - Кино",
    "Троллейбус - Кино",
    "Алюминиевые огурцы - Кино",
    "Танцевать - Кино",
    "Дождь для нас - Кино",
    "Мы хотим танцевать - Кино",
    "Красно-желтые дни - Кино",
    "Генерал - Кино",
    "Бошетунмай - Кино",
    "Сказка - Кино",
    "Буги-вуги - Кино",
    "Мой любимый город - Кино",
    "Возьми моё сердце - Кино",
    "Я объявляю свой дом безъядерной зоной - Кино",
    "Игра - Кино",
    "Раньше в твоих глазах - Кино",
    "Просто хочешь ты знать - Кино",
    "Скоро будет концерт - Кино",
    "Это - любовь - Кино",
    "Я хочу быть с тобой - Кино",
    "Странная сказка - Кино",
    "Мальчик-кино - Кино",
    "На кухне - Кино",
    "Солнечные дни - Кино",
    "Уходи - Кино",
    "Дети проходных дворов - Кино",
    "Мой друг - художник - Кино",
    "Время есть, а денег нет - Кино",
    "Сахарный бублик - Кино",
    "Я иду по улице - Кино",
    "Ассорти - Кино",
    "Попробуй спеть вместе со мной - Кино",
    "Последний герой - Кино",
    "Фильмы - Кино",
    "Белая ночь - Кино",
    "Без десяти - Кино",
    "Верь мне - Кино",
    "Семь дней - Кино",
    "Малыш - Кино",
    "Солнечный заяц - Кино",
    "Это не шутка - Кино",
    "Ты мог бы быть героем - Кино",
    "Наша жизнь - Кино",
    "Кто-то из нас - Кино",
    "Сделано в России - Кино",
    "Боль - Кино",
    "Весна - Кино",
    "Невесёлая песня - Кино",
    "Дорога - Кино",
    "Моё сердце - Кино",
    "Ты любила меня - Кино",
    "Я - змея - Кино",
    "Счастье - Кино",
    "Лето - Кино",
    "Всё хорошо - Кино",
    "Кино - это навсегда - Кино",
    "В нашем доме - Кино",
    "Завтра - Кино",
    "Трамвай - Кино",
    "Новый день - Кино",
    "Окно - Кино",
    "Утро - Кино",
    "Город - Кино",
    "Небо - Кино",
    "Тень - Кино",
    "Звезда - Кино",
    "Путь - Кино",
    "Сон - Кино",
    "Тишина - Кино",
    "Эхо - Кино",
    "Ветер - Кино",
    "Дождь - Кино",
    "Снег - Кино",
    "Туман - Кино",
    "Радуга - Кино",
    "Море - Кино",
    "Солнце - Кино",
    "Луна - Кино",
    "Облака - Кино",
    "Гроза - Кино",
    "Молния - Кино",
    "Гром - Кино",
    "Земля - Кино",
    "Огонь - Кино",
    "Вода - Кино",
    "Воздух - Кино",
    "Космос - Кино",
    "Небо и земля - Кино",
    "Счастье есть - Кино",
    "Я люблю тебя - Кино",
    "Ты и я - Кино",
    "Мы вместе - Кино",
    "Навеки - Кино",
    "Навсегда - Кино",
    "Бесконечность - Кино",
    "Вечность - Кино",
    "Мгновение - Кино",
    "Секунда - Кино",
    "Час - Кино",
    "День - Кино",
    "Рассвет - Кино",
    "Закат - Кино",
    "Полдень - Кино",
    "Полночь - Кино",
    "Вечер - Кино",
    "Шёпот - Кино",
    "Крик - Кино",
    "Молчание - Кино",
    "Взгляд - Кино",
    "Улыбка - Кино",
    "Смех - Кино",
    "Плач - Кино",
    "Танец - Кино",
    "Песня - Кино",
    "Слово - Кино",
    "Буква - Кино",
    "Звук - Кино",
    "Нота - Кино",
    "Аккорд - Кино",
    "Мелодия - Кино",
    "Ритм - Кино",
    "Темп - Кино",
    "Пауза - Кино",
    "Голос - Кино",
    "Сердце - Кино",
    "Душа - Кино",
    "Мысль - Кино",
    "Идея - Кино",
    "Мечта - Кино",
    "Реальность - Кино",
    "Фантазия - Кино",
    "Быль - Кино",
    "Правда - Кино",
    "Ложь - Кино",
    "Истина - Кино",
    "Добро - Кино",
    "Зло - Кино",
    "Свет - Кино",
    "Тьма - Кино",
    "Мрак - Кино",
    "Сияние - Кино",
    "Блеск - Кино",
    "Отражение - Кино",
    "Зеркало - Кино",
    "Стекло - Кино",
    "Камень - Кино",
    "Металл - Кино",
    "Дерево - Кино",
    "Цветок - Кино",
    "Трава - Кино",
    "Лист - Кино",
    "Ветка - Кино",
    "Корень - Кино",
    "Плод - Кино",
    "Семя - Кино",
    "Эфир - Кино",
    "Пространство - Кино",
    "Время - Кино",
    "Событие - Кино",
    "Факт - Кино",
    "Чудо - Кино",
    "Тайна - Кино",
    "Загадка - Кино",
    "Ответ - Кино",
    "Вопрос - Кино",
    "Тропа - Кино",
    "Трасса - Кино",
    "Магистраль - Кино",
    "Перекрёсток - Кино",
    "Поворот - Кино",
    "Тупик - Кино",
    "Выход - Кино",
    "Вход - Кино",
    "Дверь - Кино",
    "Крыша - Кино",
    "Пол - Кино",
    "Потолок - Кино",
    "Стена - Кино",
    "Угол - Кино",
    "Центр - Кино",
    "Край - Кино",
    "Грань - Кино",
    "Горизонт - Кино",
    "Планета - Кино",
    "Галактика - Кино",
    "Вселенная - Кино",
    "Мироздание - Кино",
    "Атом - Кино",
    "Молекула - Кино",
    "Клетка - Кино",
    "Орган - Кино",
    "Тело - Кино",
    "Чувство - Кино",
    "Эмоция - Кино",
    "Настроение - Кино",
    "Характер - Кино",
    "Судьба - Кино",
    "Рок - Кино",
    "Случай - Кино",
    "Закон - Кино",
    "Порядок - Кино",
    "Хаос - Кино",
    "Гармония - Кино",
    "Диссонанс - Кино",
    "Шум - Кино",
    "Гул - Кино",
    "Рёв - Кино",
    "Вздох - Кино",
    "Выдох - Кино",
    "Дыхание - Кино",
    "Жизнь - Кино",
    "Смерть - Кино",
    "Бессмертие - Кино",
    "Минута - Кино",
    "Creep - Radiohead",
    "High and Dry - Radiohead",
    "Fake Plastic Trees - Radiohead",
    "Karma Police - Radiohead",
    "Paranoid Android - Radiohead",
    "No Surprises - Radiohead",
    "Exit Music (For a Film) - Radiohead",
    "Street Spirit (Fade Out) - Radiohead",
    "Pyramid Song - Radiohead",
    "Idioteque - Radiohead",
    "Everything in Its Right Place - Radiohead",
    "How to Disappear Completely - Radiohead",
    "There There - Radiohead",
    "2 + 2 = 5 - Radiohead",
    "Jigsaw Falling into Place - Radiohead",
    "Reckoner - Radiohead",
    "House of Cards - Radiohead",
    "Videotape - Radiohead",
    "Lotus Flower - Radiohead",
    "Burn the Witch - Radiohead",
    "Daydreaming - Radiohead",
    "Present Tense - Radiohead",
    "True Love Waits - Radiohead",
    "Let Down - Radiohead",
    "The Bends - Radiohead",
    "My Iron Lung - Radiohead",
    "Just - Radiohead",
    "Planet Telex - Radiohead",
    "Black Star - Radiohead",
    "Sulk - Radiohead",
    "Bones - Radiohead",
    "Nice Dream - Radiohead",
    "The Tourist - Radiohead",
    "Climbing Up the Walls - Radiohead",
    "Electioneering - Radiohead",
    "Fitter Happier - Radiohead",
    "Subterranean Homesick Alien - Radiohead",
    "Airbag - Radiohead",
    "Lucky - Radiohead",
    "Meeting in the Aisle - Radiohead",
    "Pulk/Pull Revolving Doors - Radiohead",
    "Packt Like Sardines in a Crushd Tin Box - Radiohead",
    "Knives Out - Radiohead",
    "Dollars and Cents - Radiohead",
    "I Might Be Wrong - Radiohead",
    "Life in a Glasshouse - Radiohead",
    "Morning Bell - Radiohead",
    "Like Spinning Plates - Radiohead",
    "A Punchup at a Wedding - Radiohead",
    "Myxomatosis - Radiohead",
    "Sit Down. Stand Up. - Radiohead",
    "Go to Sleep - Radiohead",
    "Where I End and You Begin - Radiohead",
    "We Suck Young Blood - Radiohead",
    "I Will - Radiohead",
    "A Wolf at the Door - Radiohead",
    "15 Step - Radiohead",
    "Bodysnatchers - Radiohead",
    "Nude - Radiohead",
    "Weird Fishes/Arpeggi - Radiohead",
    "All I Need - Radiohead",
    "Faust Arp - Radiohead",
    "Down Is the New Up - Radiohead",
    "4 Minute Warning - Radiohead",
    "Bloom - Radiohead",
    "Feral - Radiohead",
    "Little by Little - Radiohead",
    "Codex - Radiohead",
    "Give Up the Ghost - Radiohead",
    "Separator - Radiohead",
    "The Daily Mail - Radiohead",
    "Staircase - Radiohead",
    "Come to Your Senses - Radiohead",
    "Smoke on the Water - Deep Purple",
    "Highway Star - Deep Purple",
    "Perfect Strangers - Deep Purple",
    "Child in Time - Deep Purple",
    "Black Night - Deep Purple",
    "Burn - Deep Purple",
    "Stormbringer - Deep Purple",
    "Knocking at Your Back Door - Deep Purple",
    "Soldier of Fortune - Deep Purple",
    "Woman from Tokyo - Deep Purple",
    "Space Truckin' - Deep Purple",
    "Fireball - Deep Purple",
    "Speed King - Deep Purple",
    "Bloodsucker - Deep Purple",
    "The Mule - Deep Purple",
    "Hush - Deep Purple",
    "Kentucky Woman - Deep Purple",
    "River Deep – Mountain High - Deep Purple",
    "Dust in the Wind - Kansas",
    "Carry On Wayward Son - Kansas",
    "Point of Know Return - Kansas",
    "The Wall - Kansas",
    "Miracles Out of Nowhere - Kansas",
    "Leftoverture - Kansas",
    "Song for America - Kansas",
    "Icarus - Kansas",
    "99 Luftballons - Nena",
    "Du hast - Rammstein",
    "Sonne - Rammstein",
    "Links 2-3-4 - Rammstein",
    "Feuer frei! - Rammstein",
    "Mein Herz brennt - Rammstein",
    "Amerika - Rammstein",
    "Ich will - Rammstein",
    "Keine Lust - Rammstein",
    "Mutter - Rammstein",
    "Косил Ясь конюшину - Песняры",
    "Валенки - (рус. нар.)",
    "Подмосковные вечера - (рус.)",
    "Ой, то не вечер - (рус. нар.)",
    "Still Loving You - Scorpions",
    "Wind of Change - Scorpions",
    "Rock You Like a Hurricane - Scorpions",
    "The Zoo - Scorpions",
    "No One Like You - Scorpions",
    "Big City Nights - Scorpions",
    "Rhythm of Love - Scorpions",
    "Send Me an Angel - Scorpions",
    "Sukiyaki - Kyu Sakamoto",
    "Yatta! - Green Green",
    "Dragostea Din Tei - O-Zone",
    "Despre tine - O-Zone",
    "Nu ma lasa - O-Zone",
    "Ma Ya Hi - O-Zone",
    "Gangnam Style - PSY",
    "Gentleman - PSY",
    "Daddy - PSY feat. CL",
    "New Face - PSY",
    "I LUV IT - PSY",
    "Bomb - PSY",
    "Alors on danse - Stromae",
    "Tous les mêmes - Stromae",
    "Formidable - Stromae",
    "Quand c'est? - Stromae",
    "Santé - Stromae",
    "L'enfer - Stromae",
    "Fils de joie - Stromae",
    "Mauvais œil - Stromae",
    "Peace or Violence - Stromae",
    "Je veux - Zaz",
    "Les passants - Zaz",
    "Le long de la route - Zaz",
    "On ira - Zaz",
    "La vie en rose - Édith Piaf",
    "Non, je ne regrette rien - Édith Piaf",
    "Milord - Édith Piaf",
    "Padam... Padam... - Édith Piaf",
    "Hymne à l'amour - Édith Piaf",
    "L'accordéoniste - Édith Piaf",
    "La Bamba - Ritchie Valens",
    "La Cumparsita - (танго)",
    "Quizás, Quizás, Quizás - Nat King Cole",
    "Bésame Mucho - Consuelo Velázquez",
    "Solamente una vez - (исп.)",
    "Amor Eterno - (исп.)",
    "Macarena - Los Del Rio",
    "Aserejé - Las Ketchup",
    "Con te partirò - Andrea Bocelli",
    "Time to Say Goodbye - Andrea Bocelli & Sarah Brightman",
    "Caruso - Lucio Dalla",
    "O sole mio - (неаполит.)",
    "Volare - Domenico Modugno",
    "Nel blu dipinto di blu - Domenico Modugno",
    "My Way - Frank Sinatra",
    "New York, New York - Frank Sinatra",
    "Fly Me to the Moon - Frank Sinatra",
    "I Did It My Way - Frank Sinatra",
    "Take Five - Dave Brubeck Quartet",
    "Blue Rondo à la Turk - Dave Brubeck",
    "Unsquare Dance - Dave Brubeck",
    "In a Sentimental Mood - Duke Ellington & John Coltrane",
    "Take the 'A' Train - Duke Ellington",
    "Mood Indigo - Duke Ellington",
    "Sophisticated Lady - Duke Ellington",
    "Caravan - Duke Ellington",
    "So What - Miles Davis",
    "All Blues - Miles Davis",
    "Freddie Freeloader - Miles Davis",
    "Kind of Blue - Miles Davis",
    "Blue in Green - Miles Davis",
    "Round Midnight - Thelonious Monk",
    "Epistrophy - Thelonious Monk",
    "Straight, No Chaser - Thelonious Monk",
    "Ruby, My Dear - Thelonious Monk",
    "Well You Needn't - Thelonious Monk",
    "Giant Steps - John Coltrane",
    "My Favorite Things - John Coltrane",
    "Naima - John Coltrane",
    "Blue Train - John Coltrane",
    "Equinox - John Coltrane",
    "A Love Supreme - John Coltrane",
    "Lush Life - Billy Strayhorn",
    "Easy on Me - Adele",
    "Set Fire to the Rain - Adele",
    "Skyfall - Adele",
    "Hello - Adele",
    "When We Were Young - Adele",
    "Water Under the Bridge - Adele",
    "Chasing Pavements - Adele",
    "All I Ask - Adele",
    "Shake It Off - Taylor Swift",
    "Blank Space - Taylor Swift",
    "Bad Blood - Taylor Swift",
    "Wildest Dreams - Taylor Swift",
    "Style - Taylor Swift",
    "Delicate - Taylor Swift",
    "Lover - Taylor Swift",
    "Cruel Summer - Taylor Swift",
    "Cardigan - Taylor Swift",
    "Willow - Taylor Swift",
    "Anti-Hero - Taylor Swift",
    "Lavender Haze - Taylor Swift",
    "Karma - Taylor Swift",
    "Maroon - Taylor Swift",
    "Fade Into You - Mazzy Star",
    "Sweet Jane - The Velvet Underground",
    "Perfect Day - Lou Reed",
    "Walk on the Wild Side - Lou Reed",
    "Satellite of Love - Lou Reed",
    "Передвижник - ДДТ",
    "Что такое осень - ДДТ",
    "Дождь - ДДТ",
    "Россия - ДДТ",
    "Свобода - ДДТ",
    "Не стреляй - ДДТ",
    "В последнюю осень - ДДТ",
    "Просвистела - ДДТ",
    "Поле - ДДТ",
    "Куда ты - ДДТ",
    "Февраль - ДДТ",
    "Летели облака - ДДТ",
    "Это всё - ДДТ",
    "Продавец дождя - Наутилус Помпилиус",
    "Скованные одной цепью - Наутилус",
    "Я хочу быть с тобой - Наутилус",
    "Гудбай, Америка - Наутилус",
    "Князь тишины - Наутилус",
    "Зверь - Наутилус",
    "Черные птицы - Наутилус",
    "Тутанхамон - Наутилус",
    "Дыхание - Наутилус",
    "Стриптиз - Наутилус",
    "Бриллиантовые дороги - Наутилус",
    "Утро Полины - Наутилус",
    "Доктор Шнапс - Наутилус",
    "Одинокая птица - Наутилус",
    "Прогулки по воде - Наутилус",
    "Хлоп-хлоп - Наутилус"
]

# ----- AI ФУНКЦИИ -----
async def generate_icebreakers(user1: User, user2: User) -> List[str]:
    prompt = (
        f"Пользователь 1: {user1.name or 'Без имени'}, любимые группы: {user1.favorite_bands or 'не указаны'}, "
        f"песни: {user1.favorite_songs or 'не указаны'}, жанры: {user1.favorite_genres or 'не указаны'}, "
        f"био: {user1.bio or 'не указано'}, интересы: {user1.interests or 'не указаны'}.\n"
        f"Пользователь 2: {user2.name or 'Без имени'}, любимые группы: {user2.favorite_bands or 'не указаны'}, "
        f"песни: {user2.favorite_songs or 'не указаны'}, жанры: {user2.favorite_genres or 'не указаны'}, "
        f"био: {user2.bio or 'не указано'}, интересы: {user2.interests or 'не указаны'}.\n\n"
        "Сгенерируй 5 персонализированных фраз для начала разговора, которые подойдут этим двоим. "
        "Учти их общие музыкальные вкусы, интересы и цели. Фразы должны быть естественными, дружелюбными и вовлекающими. "
        "Верни только список фраз, каждая с новой строки, без нумерации."
    )
    try:
        payload = Chat(
            messages=[Messages(role=MessagesRole.USER, content=prompt)],
            temperature=0.8,
            max_tokens=200
        )
        response = await client.achat(payload)
        text = response.choices[0].message.content.strip()
        lines = [line.strip() for line in text.split("\n") if line.strip()]
        return lines[:5]
    except Exception as e:
        logger.error(f"AI icebreakers failed: {e}")
        return ["Привет! Заметил, что мы оба любим музыку. Какую песню последнюю слушал?",]

async def analyze_music_taste(user: User) -> str:
    prompt = (
        f"Пользователь: {user.name or 'Без имени'}, любимые группы: {user.favorite_bands or 'не указаны'}, "
        f"песни: {user.favorite_songs or 'не указаны'}, жанры: {user.favorite_genres or 'не указаны'}, "
        f"био: {user.bio or 'не указано'}, интересы: {user.interests or 'не указаны'}.\n\n"
        "Напиши краткий (2-3 предложения) анализ музыкального вкуса этого человека. "
        "Опиши, какие направления ему близки, какой вайб он несёт, и что это говорит о его личности. "
        "Будь дружелюбным и интересным."
    )
    try:
        payload = Chat(
            messages=[Messages(role=MessagesRole.USER, content=prompt)],
            temperature=0.7,
            max_tokens=120
        )
        response = await client.achat(payload)
        return response.choices[0].message.content.strip()
    except Exception as e:
        logger.error(f"AI music analysis failed: {e}")
        return "Анализ пока недоступен. Попробуй позже."

async def get_match_recommendation(user: User, candidates: List[User]) -> Dict[str, Any]:
    if not candidates:
        return {"user": None, "explanation": "Нет кандидатов для анализа."}
    top_candidates = candidates[:5]
    candidates_text = ""
    for i, u in enumerate(top_candidates, 1):
        candidates_text += (
            f"Кандидат {i}: {u.name or 'Без имени'}, группы: {u.favorite_bands or 'не указаны'}, "
            f"песни: {u.favorite_songs or 'не указаны'}, жанры: {u.favorite_genres or 'не указаны'}, "
            f"био: {u.bio or 'не указано'}, интересы: {u.interests or 'не указаны'}\n"
        )
    prompt = (
        f"Пользователь: {user.name or 'Без имени'}, любимые группы: {user.favorite_bands or 'не указаны'}, "
        f"песни: {user.favorite_songs or 'не указаны'}, жанры: {user.favorite_genres or 'не указаны'}, "
        f"био: {user.bio or 'не указано'}, интересы: {user.interests or 'не указаны'}.\n\n"
        f"Кандидаты:\n{candidates_text}\n"
        "Выбери одного кандидата, который лучше всего подходит этому пользователю. "
        "Учитывай общие музыкальные вкусы, интересы, цели и совместимость по био. "
        "Ответ должен быть в формате JSON с полями: 'best_index' (номер кандидата от 1 до N) и "
        "'explanation' (краткое объяснение, почему этот кандидат подходит, 2-3 предложения)."
        "Верни только JSON."
    )
    try:
        payload = Chat(
            messages=[Messages(role=MessagesRole.USER, content=prompt)],
            temperature=0.5,
            max_tokens=150
        )
        response = await client.achat(payload)
        data = json.loads(response.choices[0].message.content.strip())
        idx = data.get("best_index", 1) - 1
        if 0 <= idx < len(top_candidates):
            return {"user": top_candidates[idx], "explanation": data.get("explanation", "Совпадение на основе музыкальных предпочтений.")}
        else:
            return {"user": None, "explanation": "Не удалось выбрать."}
    except Exception as e:
        logger.error(f"AI match recommendation failed: {e}")
        return {"user": None, "explanation": "Ошибка AI. Попробуй позже."}

async def generate_blind_date_questions(song: str, user1: User, user2: User) -> List[str]:
    prompt = (
        f"Для музыкального свидания вслепую выбрана песня: {song}.\n"
        f"Участник 1: {user1.name or 'Без имени'}, био: {user1.bio or 'не указано'}, интересы: {user1.interests or 'не указаны'}.\n"
        f"Участник 2: {user2.name or 'Без имени'}, био: {user2.bio or 'не указано'}, интересы: {user2.interests or 'не указаны'}.\n\n"
        "Сгенерируй 3 вопроса для обсуждения этой песни, которые помогут участникам лучше узнать друг друга. "
        "Вопросы должны быть открытыми, вовлекающими и связанными с музыкой, чувствами и личным опытом. "
        "Верни только список вопросов, каждый с новой строки, без нумерации."
    )
    try:
        payload = Chat(
            messages=[Messages(role=MessagesRole.USER, content=prompt)],
            temperature=0.8,
            max_tokens=150
        )
        response = await client.achat(payload)
        text = response.choices[0].message.content.strip()
        lines = [line.strip() for line in text.split("\n") if line.strip()]
        return lines[:3]
    except Exception as e:
        logger.error(f"AI blind date questions failed: {e}")
        return ["Что тебе больше всего нравится в этой песне?", "Какие эмоции она у тебя вызывает?", "С каким моментом жизни она ассоциируется?"]